name: Build and Deploy
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          node build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/
  deploy: # See https://github.com/actions/deploy-pages#usage
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
